#!/bin/bash
# Pharmyrus V5.0 - Essential Commands Reference
# Quick reference for common operations

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         PHARMYRUS V5.0 - ESSENTIAL COMMANDS                    ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}📁 PROJECT STRUCTURE${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cd /home/claude/pharmyrus-v5"
echo "tree -L 2 -I '__pycache__|*.pyc|venv|.venv'"
echo ""

echo -e "${BLUE}🔧 LOCAL DEVELOPMENT${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Install dependencies"
echo "pip install -r requirements.txt"
echo ""
echo "# Install browsers"
echo "playwright install chromium firefox webkit"
echo ""
echo "# Set environment"
echo "export EPO_CONSUMER_KEY='G5wJypxeg0GXEJoMGP37tdK370aKxeMszGKAkD6QaR0yiR5X'"
echo "export EPO_CONSUMER_SECRET='zg5AJ0EDzXdJey3GaFNM8ztMVxHKXRrAihXH93iS5ZAzKPAP'"
echo "export GROK_API_KEY='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'"
echo ""
echo "# Run server"
echo "python main.py"
echo ""
echo "# Test health"
echo "curl http://localhost:8000/health"
echo ""

echo -e "${BLUE}🧪 TESTING${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Run integration tests"
echo "python tests/integration_test.py"
echo ""
echo "# Test specific component"
echo "python -c 'from src.core.super_crawler import SuperCrawler; import asyncio; asyncio.run(SuperCrawler().test())'"
echo ""
echo "# Check compilation"
echo "python -m py_compile main.py src/**/*.py"
echo ""

echo -e "${BLUE}🐳 DOCKER${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Build image"
echo "docker build -t pharmyrus-v5 ."
echo ""
echo "# Run container"
echo "docker run -d --name pharmyrus -p 8000:8000 \\"
echo "  -e EPO_CONSUMER_KEY='xxx' \\"
echo "  -e EPO_CONSUMER_SECRET='xxx' \\"
echo "  pharmyrus-v5"
echo ""
echo "# Check logs"
echo "docker logs pharmyrus"
echo ""
echo "# Stop & remove"
echo "docker stop pharmyrus && docker rm pharmyrus"
echo ""

echo -e "${BLUE}🚂 RAILWAY DEPLOYMENT${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Quick deploy"
echo "./deploy.sh  # Select option 2"
echo ""
echo "# Manual deploy"
echo "railway login"
echo "railway link"
echo "railway up"
echo ""
echo "# Set variables"
echo "railway variables set EPO_CONSUMER_KEY='xxx'"
echo "railway variables set EPO_CONSUMER_SECRET='xxx'"
echo "railway variables set GROK_API_KEY='xxx'"
echo ""
echo "# Get URL"
echo "railway domain"
echo ""
echo "# Watch logs"
echo "railway logs"
echo ""

echo -e "${BLUE}📡 API TESTING${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Set base URL"
echo "export BASE_URL='http://localhost:8000'"
echo "# Or production"
echo "export BASE_URL='https://your-app.up.railway.app'"
echo ""
echo "# Health check"
echo "curl \$BASE_URL/health"
echo ""
echo "# System stats"
echo "curl \$BASE_URL/api/v1/stats"
echo ""
echo "# Comprehensive search"
echo "curl -X POST \$BASE_URL/api/v1/search \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"molecule\": \"Aspirin\"}'"
echo ""
echo "# Patents only"
echo "curl -X POST \$BASE_URL/api/v1/patents/search \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"molecule\": \"Darolutamide\"}'"
echo ""
echo "# Clinical trials only"
echo "curl -X POST \$BASE_URL/api/v1/research/clinical-trials \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"molecule\": \"Olaparib\"}'"
echo ""
echo "# PubChem data"
echo "curl \$BASE_URL/api/v1/molecule/Venetoclax/pubchem"
echo ""

echo -e "${BLUE}🔍 DEBUGGING${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Check failed URLs"
echo "curl \$BASE_URL/api/v1/debug/failed-urls"
echo ""
echo "# View local debug logs"
echo "ls -lh debug_logs/"
echo "cat debug_logs/errors/*.json"
echo ""
echo "# Check Railway logs"
echo "railway logs --tail 100"
echo ""

echo -e "${BLUE}📊 BASELINE VALIDATION${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Test all Cortellis molecules"
echo "for mol in Darolutamide Ixazomib Olaparib Venetoclax Niraparib; do"
echo "  echo \"Testing \$mol...\""
echo "  curl -s -X POST \$BASE_URL/api/v1/search \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"molecule\": \"'\$mol'\"}' | jq '.patents.total'"
echo "  sleep 10"
echo "done"
echo ""

echo -e "${BLUE}📖 DOCUMENTATION${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cat QUICKSTART.md              # 5-minute setup"
echo "cat DEPLOYMENT_CHECKLIST.md    # Deployment guide"
echo "cat DOCUMENTATION_V5.md        # Full docs"
echo "cat FINAL_SUMMARY.md           # Implementation summary"
echo ""

echo -e "${BLUE}🔧 TROUBLESHOOTING${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Check if port is in use"
echo "lsof -i :8000"
echo ""
echo "# Kill process on port"
echo "kill -9 \$(lsof -t -i:8000)"
echo ""
echo "# Check Python version"
echo "python --version  # Should be 3.12+"
echo ""
echo "# Check disk space"
echo "df -h"
echo ""
echo "# Check memory"
echo "free -h"
echo ""

echo -e "${BLUE}📦 PROJECT MANAGEMENT${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Create backup"
echo "tar -czf pharmyrus-backup-\$(date +%Y%m%d).tar.gz pharmyrus-v5/"
echo ""
echo "# Count lines of code"
echo "find . -name '*.py' -not -path './venv/*' | xargs wc -l"
echo ""
echo "# Check git status"
echo "git status"
echo "git log --oneline -10"
echo ""

echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ For complete documentation, see:${NC}"
echo "   • QUICKSTART.md"
echo "   • DEPLOYMENT_CHECKLIST.md"
echo "   • DOCUMENTATION_V5.md"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
